name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Deno version
        run: echo deno --version

      - name: Check Any Type Errors
        run: deno cache src/mod.ts

      - name: Can Compile To Dist
        run: npm run compile # mainly to check if there are any errors when running this command

      - name: Basic Example Can Be Compiled
        run: |
          cd examples/deno
          deno bundle --config tsconfig.json components/App.ts components/app.js
          cd ../node
          npm i
          node_modules/.bin/webpack --config webpack.config.js
          cd ../browser
          echo "No build step so no testing here"

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: echo "Is this something we want?" #deno fmt --check --ignore=dist

      - name: Linter
        run: npm run lint